apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-config-map
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://everest-db.default.svc.cluster.local:5432/employee
  SPRING_DATASOURCE_USERNAME: everest_emp
  SPRING_DATASOURCE_PASSWORD: everestpw
  #SPRING_ZIPKIN_BASE-URL: http://everest-zipkin.default.svc.cluster.local:9411/
  #SPRING_CONFIG_IMPORT: optional:configserver:http://cloud-config-server-svc.default.svc.cluster.local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-app
  labels:
    app: employee-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : employee-service-app
  template:
    metadata:
      labels:
        app: employee-service-app
    spec:
      containers:
      - name: employee-service-app
        image: shkumar45/everest-employee:0.0.3
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        envFrom:
          - configMapRef:
              name: employee-config-map

---


apiVersion: v1
kind: Service
metadata:
  name:  employee-service-svc
spec:
  #type: NodePort
  selector:
    app:  employee-service-app
  ports:
  - port:  80
    targetPort:  8086
    #nodePort: 30001





